builds:
  - binary: saw
    goos:
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    env:
      - CGO_ENANBLED=0

archive:
  format: tar.gz
  files:
    - LICENSE

brew:
  name: saw

  github:
    owner: absolutarin
    name: homebrew-saw

  commit_author:
    name: absolutarin
    email: mailme@mail.com

  folder: Formula
  homepage: "https://github.com/absolutarin/saw"
  description: "Fast, multipurpose tool for AWS CloudWatch Logs"

git:
  short_hash: true

nfpm:
  vendor: Arindam Chanda
  homepage: https://github.com/absolutarin/saw
  maintainer: Arindam Chanda
  description: Fast, multipurpose CLI tool for AWS CloudWatch Logs written in Go
  license: MIT
  formats:
    - deb
    - rpm
